いいね機能
UJr-creator/tenkue-board-r001 pull request #14
Opened 2020-12-13 10:42 UTC by riku103

## 概要
### 1. 1ユーザーあたり、1投稿に対して1回のみいいねが押せるようになっている
### 2. いいねが押されている状態でもう一度いいねを押すと、いいねが取り消される
### 3. 未ログイン時にはいいねボタンを押せないようになっている
### 4. いいねをカウントできている

## 確認したこと
### 1. ログインしているユーザーは1投稿に対して1回のみいいねができる
### 2. いいねが押されている状態でもう一度押すといいねが取り消される
### 3. いいねのカウントできる

![いいね機能](https://user-images.githubusercontent.com/67620156/102009428-b3655880-3d7a-11eb-8c0e-15e9f7ed6568.gif)

### 4. 未ログイン時にいいねを押すと新規登録画面に遷移する
![未ログイン時いいね押せない](https://user-images.githubusercontent.com/67620156/102009464-ec9dc880-3d7a-11eb-91bc-ece36cbaa7c9.gif)

2020-12-13 11:06 UTC, UJr-creator commented on app/assets/javascripts/likes.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
このファイルは不要かなと思いました。

2020-12-13 11:06 UTC, UJr-creator commented on app/assets/stylesheets/likes.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
このファイルは不要かなと思いました。

2020-12-13 11:15 UTC, riku103 commented on app/models/user.rb
> +  has_many :likes, dependent: :destroy
確かに今回の実装では関係ないのでいらないですね！
消しておきます。

2020-12-13 11:34 UTC, UJr-creator approved these changes
LGTMです！

2020-12-13 14:29 UTC, sew-sou19 requested changes
レビューしました！
もう少しだけ調整お願いします！

2020-12-13 14:29 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    @like = Like.create(user_id: current_user.id, post_id: @post.id)
ここインスタンス変数にする必要ありますかね、、？
テンプレートファイルに値を渡さない場合、混乱を招くので変数化は不要かと思います！

2020-12-13 14:29 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    @like = current_user.likes.find_by(post_id: @post.id)
ここも同じです！

2020-12-13 14:29 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    redirect_back(fallback_location: root_path)
掲示板詳細画面でいいねを押した時は、該当の掲示板の詳細画面にリダイレクトするのが理想ですねー！
※ここはプラスアルファなので、対応しなくても大丈夫です。

2020-12-13 14:29 UTC, sew-sou19 commented on app/models/like.rb
> +  validates_uniqueness_of :post_id, scope: :user_id
ここはモデルでもそうですが、DB設計で制限すべき気もしますね、、、
ただ、間違ってるわけではないのでこのままでも大丈夫かと！

2020-12-14 01:02 UTC, riku103 commented on app/models/like.rb
> +  validates_uniqueness_of :post_id, scope: :user_id
レビューありがとうございます！
インスタンス変数を削除しました。

2020-12-14 03:49 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-14 04:32 UTC, merged