バリデーションの正規表現、テストコード記載
UJr-creator/tenkue-board-r001 pull request #15
Opened 2020-12-13 12:02 UTC by UJr-creator

### 実施したこと
1. バリデーションの正規表現実装（Userモデル、Postモデル、Commentモデル）
2. テストコードの記載（Userモデル、Postモデル、Commentモデル）

### 各種条件
- Userモデル
  - メールアドレスに全角文字が含まれていないこと
  - パスワードは8文字以上32文字以下であること
  - パスワードは半角英字と半角数字のいずれとも含まれていること
- Postモデル
  - 投稿内容がnot null
  - 投稿内容は140文字以内
- Commentモデル
  - コメント内容がnot null
  - コメント内容は140文字以内

### 動画
![テストの実行](https://user-images.githubusercontent.com/65746218/102011227-42c43900-3d86-11eb-9272-3de582256bcf.gif)

2020-12-13 13:13 UTC, riku103 approved these changes

2020-12-13 14:37 UTC, sew-sou19 requested changes
レビューしました！
追加のテストをお願いします！！

2020-12-13 14:37 UTC, sew-sou19 commented on spec/models/comment_spec.rb
> +  it "コメントはnot null" do
これだと何をテストしてるのかが明確でないので、分かりやすく記述しましょう！
例：コメントが空白でない時はコメントを登録できること、など

2020-12-13 14:37 UTC, sew-sou19 commented on spec/models/comment_spec.rb
> +  end
テストは、思った通りの動作をする時だけでなく、バリデーション等に反した時に登録できないことまで確認しましょう！

ここで言えば、
- コメントが空白の時は登録できない
- コメントが141文字以上の時は登録できない

もテストしましょう！

2020-12-13 14:37 UTC, sew-sou19 commented on spec/models/comment_spec.rb
> +  end
あ、逆でしたね。
バリデーションに反した時に登録できないこと、だけでなく、適正な値の時に登録できることのテストも必要です！

2020-12-13 14:37 UTC, sew-sou19 commented on spec/models/post_spec.rb
> +  it "Postはnot null" do
ここもcomment_specと同じ指摘です！
1. テストのタイトルをわかりやすく記述する
2. 適正な値の時に登録できることをテストする

2020-12-13 14:37 UTC, sew-sou19 commented on spec/models/user_spec.rb
> +  it "メールアドレスには全角文字が含まれていない" do
ここもcomment_specと同じ指摘です！
1. テストのタイトルをわかりやすく記述する
2. 適正な値の時に登録できることをテストする

2020-12-14 12:56 UTC, sew-sou19 commented
コンフリクトを解消しましょう！

2020-12-14 12:58 UTC, sew-sou19 requested changes
コードの修正は不要ですが、コンフリクトを解消してください！

2020-12-14 12:58 UTC, sew-sou19 commented on spec/models/user_spec.rb
> +  it "パスワードは8文字以下でエラーが発生" do
ここは日本語の問題なので修正は不要ですが、「エラーが発生」だとどういうエラーがどういう時に発生するのか？結局何をテストしているのか？が分からないので、シンプルに「ユーザー登録できない」で良いかと思います！

2020-12-14 13:16 UTC, sew-sou19 approved these changes
LGTMです！！

2020-12-14 13:22 UTC, merged