Edit delete
UJr-creator/tenkue-board-r001 pull request #8
Opened 2020-12-08 14:09 UTC by UJr-creator

### 実施したこと

- 投稿編集機能の実装（投稿者のみ編集画面に遷移可能）
- 投稿削除機能の実装（投稿者のみ削除可能）

### 各種条件
- 投稿者のみ編集画面に遷移可能
- 投稿者のみ削除可能
-  編集機能は新規投稿時と同じUI設計
- 未ログイン時には編集画面にアクセスできない
- 各種バリデーションが設定されやエラーメッセージが表示される（前タスクまでで実装済）

### 動画
- 投稿編集
![投稿機能](https://user-images.githubusercontent.com/65746218/101494037-2d2bc980-39aa-11eb-8d4f-a2c9f30fe777.gif)

- 削除機能
![削除機能](https://user-images.githubusercontent.com/65746218/101494077-3b79e580-39aa-11eb-963b-4a98bdfd2d4c.gif)

- ログインユーザーのみ編集ページへの遷移可能
![投稿のユーザー結びつけ](https://user-images.githubusercontent.com/65746218/101494154-50567900-39aa-11eb-9780-f22d5c2a84a5.gif)

2020-12-08 14:52 UTC, riku103 approved these changes

2020-12-08 15:15 UTC, soramm approved these changes

2020-12-09 13:00 UTC, sew-sou19 requested changes
いいですね！2点だけご確認をお願いします！

2020-12-09 13:02 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    unless @post
あ、時間かけて読み解けばなんとなくわかりました。
`@post`は、ログインしてるユーザーが投稿したもののうち、リクエストされたpost_idが一致してるものがあるか、的な絞り込みをしてるんですね。

第三者がパッと見たときにわかりにくく、可読性が落ちてしまうので避けましょう！

2020-12-09 13:07 UTC, UJr-creator commented on app/controllers/posts_controller.rb
> +    unless @post
@postにcurrent_userのpost入れております。
要はcurrent_userがいない時は、@postはnilとなり、unlessがtrueとなるかなと考えております。
@postがない=current_userではない時、ホームのページにredirectするという流れの想定です。
ややこしいきもするので、unless @post.user_id == current_user.idにした方が良いでしょうか？

2020-12-09 13:10 UTC, UJr-creator commented on app/views/posts/edit.html.erb
> +      <div class="form_area">
posts/new（新規投稿機能）でしょうか？？
※勘違いでしたらすみません。
それでしたらフォームのパーシャルを設けて、new, edit両方リファクタリングしようと思います。

2020-12-09 13:13 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    unless @post
> ややこしいきもするので、unless @post.user_id == current_user.idにした方が良いでしょうか？

こちらの方が分かりやすいですね！

2020-12-09 13:13 UTC, sew-sou19 commented on app/views/posts/edit.html.erb
> +      <div class="form_area">
あああ！ごめんなさい！
おっしゃる通り、`posts/new`です！

2020-12-09 13:24 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-09 13:28 UTC, merged